services:
  prod-database:
    image: postgres:latest
    container_name: prod-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  prod-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prod-api
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_JDBC_URL: jdbc:postgresql://prod-database:5432/postgres
    depends_on:
      - prod-database

volumes:
  pgdata: