{
 "title": "PROD INDIVIDUAL DASHBOARD",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Revenue by day",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    impressions.date AS \"day\",\r\n    SUM(impressions.total_cost) AS \"total_revenue\",\r\n    SUM(clicks.total_cost) AS \"total_click_revenue\"\r\nFROM\r\n    (SELECT date, SUM(cost) AS total_cost\r\n     FROM history_impressions\r\n     GROUP BY date) impressions\r\n        LEFT JOIN\r\n    (SELECT date, SUM(cost) AS total_cost\r\n     FROM history_clicks\r\n     GROUP BY date) clicks\r\n    ON impressions.date = clicks.date\r\nGROUP BY\r\n    impressions.date\r\nORDER BY\r\n    impressions.date ASC;\r\n"
    }
   ]
  },
  {
   "title": "Advertiser count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "advertiser_count{instance=\"backend-service:8080\"}",
     "legendFormat": "advertiser count"
    }
   ]
  },
  {
   "title": "Campaign count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "campaign_count{instance=\"backend-service:8080\"}",
     "legendFormat": "Campaign count"
    }
   ]
  },
  {
   "title": "Client count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_count{instance=\"backend-service:8080\"}",
     "legendFormat": "client count"
    }
   ]
  },
  {
   "title": "Viewed count by day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"date\" AS \"day\",\r\n  COUNT(*) AS \"impressions\"\r\nFROM\r\n  history_impressions\r\nGROUP BY\r\n  \"date\"\r\nORDER BY\r\n  \"date\" ASC"
    }
   ]
  },
  {
   "title": "Click count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "click_count{instance=\"backend-service:8080\"}",
     "legendFormat": "click count"
    }
   ]
  },
  {
   "title": "view count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "view_count{instance=\"backend-service:8080\"}",
     "legendFormat": "view count"
    }
   ]
  },
  {
   "title": "revenue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "earnings{instance=\"backend-service:8080\"}",
     "legendFormat": "earnings"
    }
   ]
  },
  {
   "title": "AVG CPU USAGE 5m",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(system_cpu_usage{job=\"backend\"}[1m])*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clicked count by day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"date\" AS \"day\",\r\n  COUNT(*) AS \"clicks\"\r\nFROM\r\n  history_clicks \r\nGROUP BY\r\n  \"date\"\r\nORDER BY\r\n  \"date\" ASC"
    }
   ]
  }
 ]
}