{
 "title": "PROD INDIVIDUAL DASHBOARD",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Advertiser count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "advertiser_count{instance=\"backend-service:8080\"}",
     "legendFormat": "advertiser count"
    }
   ]
  },
  {
   "title": "Campaign count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "campaign_count{instance=\"backend-service:8080\"}",
     "legendFormat": "Campaign count"
    }
   ]
  },
  {
   "title": "Client count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "user_count{instance=\"backend-service:8080\"}",
     "legendFormat": "client count"
    }
   ]
  },
  {
   "title": "Viewed count by day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum by(day) (ads_impressions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Click count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "click_count{instance=\"backend-service:8080\"}",
     "legendFormat": "click count"
    }
   ]
  },
  {
   "title": "view count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "view_count{instance=\"backend-service:8080\"}",
     "legendFormat": "view count"
    }
   ]
  },
  {
   "title": "earnings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "earnings{instance=\"backend-service:8080\"}",
     "legendFormat": "earnings"
    }
   ]
  },
  {
   "title": "AVG CPU USAGE 5m",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(system_cpu_usage{job=\"backend\"}[1m])*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clicked count by day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 8 },
   "targets": [
    { "expr": "sum by(day) (ads_clicks_total)", "legendFormat": "__auto" }
   ]
  }
 ]
}